version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/db
    environment:
      PGUSER: ${PGUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}